spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security
    username: root
    password: 123456
  session:
    store-type: none
security:
  basic:
    enabled: false

demo:
  security:
    browser:
      loginPage : /demo-login.html
      loginType: JSON
    code:
      image:
        length: 4
        width: 180
        height: 42
        urls: /user,/user/*