
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security
    username: root
    password: 123456
  session:
    store-type: none
security:
  basic:
    enabled: false

demo:
  security:
    browser:
      loginPage : /demo-login.html
      loginType: JSON
      signUpUrl: /demo-signup.html
    code:
      image:
        length: 4
        width: 180
        height: 42
        urls:
    social:
      qq:
        app-id: 101548936
        app-secret: 6a97ce44775387a86f59ef6bce172115
        providerId: callback.do
      filterProcessUrl: /myLogin

server:
  port: 80